version: '3'
services:
  client:
    depends_on:
      - server_node
      - server_django
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    image: burakovali/client:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/client/nginx:/etc/nginx/conf.d
  server_node:
    depends_on:
      - postgres_db
    build: 
      context: ./backend/node
      dockerfile: Dockerfile
    image: burakovali/server_node:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/node/:/usr/src/app/
      - /usr/src/app/node_modules
  server_django:
    depends_on:
      - postgres_db
      - server_node
    build: 
      context: ./backend/django
      dockerfile: Dockerfile
    image: burakovali/server_django:latest
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
    build: 
      context: ./backend/db
      dockerfile: Dockerfile
    image: burakovali/todo_app_db:latest
    restart: always
    env_file:
      - ./backend/db/.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_node:/var/lib/postgresql/data/
volumes:
  postgres_data_node:
