apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-django
  namespace: prod
  labels:
    tier: prod
    app: server-django
spec:
  selector:
    matchLabels:
      tier: prod
      app: server-django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: prod
        app: server-django
    spec:
      containers:
      - name: server-django
        image: docker.io/burakovali/server-django:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
      # nodeSelector:
      #   tier: prod
      # tolerations:
      #   - key: "tier"
      #     operator: "Equal"
      #     value: "prod"
      #     effect: "NoSchedule"
      #   - key: "service"
      #     operator: "Equal"
      #     value: "django"
      #     effect: "NoSchedule"
