apiVersion: v1
kind: Service
metadata:
  name: server-django
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: server-django
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
