apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-test-rb
  namespace: test
subjects:
- kind: User
  name: junior@team.in
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io