apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sr-production-rb
  namespace: prod
subjects:
- kind: User
  name: senior@team.in
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io