apiVersion: v1
kind: Service
metadata:
  name: server-node
  namespace: prod
spec:
  type: NodePort
  selector:
    app: server-node
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
