apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
#   namespace: prod
spec:
  type: {{ .Values.spec.type | repeat 5 | upper | quote }}
  app: {{ semver  }}
  
  selector:
    app: server-node
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
