# Generated by Django 3.2 on 2022-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('todo_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
