apiVersion: v1
kind: Service
metadata:
  name: client-web-svc
spec:
  type: NodePort
  selector:
    app: client-web-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80