apiVersion: v1
kind: Service
metadata:
  name: private-todo-list-penn-do-user-11122973-0.b.db.ondigitalocean.com
  namespace: prod
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 25060
    targetPort: 25060
