apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-prod-claim
  namespace: prod
  labels:
    tier: prod
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

