
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:ovaliburak/todo-app-devops-project.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true